import { lazy, Suspense, useRef, useState } from 'react'
import { MotorModel } from '../lib/plc'
import { useLabClock } from '../lib/useLabClock'
import { Seg, Stat, VizTitle } from '../components/ui'
import Prediction from '../components/Prediction'
const MachineScene = lazy(() => import('../components/MachineScene'))

function Contact({ x, y, label, value, inverted = false }: { x: number; y: number; label: string; value: boolean; inverted?: boolean }) {
  return <g transform={`translate(${x},${y})`} style={{ color: value ? 'var(--green)' : 'var(--muted)' }}><path d="M-38 0h25m0-16v32m26-32v32m0-16h25" stroke="currentColor" strokeWidth="3" />{inverted && <path d="M-20 20 20-20" stroke="currentColor" strokeWidth="2" />}<text textAnchor="middle" y="-27" fill="var(--text)" fontSize="13">{label}</text><text textAnchor="middle" y="34" fill="currentColor" fontSize="11">{value ? 'TRUE' : 'FALSE'}</text></g>
}
export default function LadderLab() {
  const model = useRef(new MotorModel()).current
  const [running, setRunning] = useState(false)
  const refresh = useLabClock(() => model.scan(), running, 300)
  const update = (change: () => void) => { change(); refresh() }
  const phase = ['Read physical inputs', 'Execute ladder logic', 'Write physical outputs'][model.phase]
  return <>
    <Prediction question="With a healthy normally closed stop button released, which instruction should pass the StopHealthy bit?" options={['XIC: the input bit is 1.', 'XIO: the switch is physically normally closed.', 'Neither: the input must be 0.']} answer={0} explanation="The released NC switch conducts, so the input bit is 1. XIC tests that bit for 1. Physical contact type and ladder instruction are different decisions. Press Stop and complete a scan to see the chain open." />
    <div className="panel"><h3>Physical devices</h3><div className="row"><button className={`btn small ${model.start ? 'on' : 'ghost'}`} aria-pressed={model.start} onClick={() => update(() => { model.start = !model.start })}>{model.start ? 'Release Start' : 'Press Start'}</button><button className={`btn small ${model.stop ? 'danger' : 'ghost'}`} aria-pressed={model.stop} onClick={() => update(() => { model.stop = !model.stop })}>{model.stop ? 'Release Stop' : 'Press Stop'}</button><button className="btn small ghost" aria-pressed={!model.wireHealthy} onClick={() => update(() => { model.wireHealthy = !model.wireHealthy })}>{model.wireHealthy ? 'Break stop wire' : 'Repair stop wire'}</button><button className="btn small ghost" aria-pressed={!model.contactorHealthy} onClick={() => update(() => { model.contactorHealthy = !model.contactorHealthy })}>{model.contactorHealthy ? 'Jam contactor' : 'Repair contactor'}</button><button className="btn small ghost" aria-pressed={!model.overloadHealthy} onClick={() => update(() => { model.overloadHealthy = !model.overloadHealthy })}>{model.overloadHealthy ? 'Trip overload' : 'Reset overload'}</button></div><p className="lesson-hint">Buttons stay pressed until released. Device changes enter the input image during the next read phase.</p></div>
    <div className="viz"><VizTitle title="24 V field wiring → input image" /><div className="signal-chain"><span>+24 V</span><b>→</b><span className={!model.stop && model.wireHealthy ? 'signal-on' : ''}>NC stop {model.stop ? 'open' : 'closed'}</span><b>→</b><span>{model.wireHealthy ? 'Wire intact' : 'Wire broken'}</span><b>→</b><span>StopHealthy = {Number(model.image.stopHealthy)}</span></div><div className="signal-chain"><span>+24 V</span><b>→</b><span>NO start {model.start ? 'closed' : 'open'}</span><b>→</b><span>Start = {Number(model.image.start)}</span><b>·</b><span>Auxiliary feedback = {Number(model.feedback)}</span></div></div>
    <div className="viz"><VizTitle title="Motor rung · a command is not feedback" legend={[{ color: 'var(--green)', label: 'True condition' }, { color: 'var(--muted)', label: 'False condition' }]} /><div className="diagram-scroll" tabIndex={0} role="region" aria-label="Motor ladder diagram; scroll horizontally on small screens"><svg viewBox="0 0 720 260" role="img" aria-label="StopHealthy and overload in series with Start or holding feedback, driving MotorCommand"><path d="M25 38v190M695 38v190M25 105H75M151 105H205M281 105H361M321 105V200H361M437 200H480V105M437 105H569M616 105H695" stroke="var(--line)" strokeWidth="3" fill="none" /><Contact x={113} y={105} label="StopHealthy" inverted={model.stopInstruction === 'XIO'} value={model.stopTest} /><Contact x={243} y={105} label="OverloadHealthy" value={model.image.overload} /><Contact x={399} y={105} label="Start" value={model.image.start} /><Contact x={399} y={200} label={model.holdSource} value={model.image.hold} /><g fill="none" stroke={model.pending ? 'var(--green)' : 'var(--muted)'} strokeWidth="3"><path d="M579 87q-20 18 0 36m27-36q20 18 0 36" /></g><text x="592" y="58" textAnchor="middle" fill="var(--text)" fontSize="13">MotorCommand</text><text x="592" y="151" textAnchor="middle" fill="var(--muted)" fontSize="12">pending {Number(model.pending)}</text></svg></div></div>
    <div className="panel"><div className="scan-phases">{['Read', 'Execute', 'Write'].map((p, i) => <span key={p} className={model.phase === i ? 'current' : ''}>{i + 1}. {p}</span>)}</div><p className="lesson-hint" role="status">Next: {phase} · completed scans {model.scans}</p><div className="row"><button className="btn small" onClick={() => update(() => model.stepPhase())} disabled={running}>Step phase</button><button className="btn small ghost" onClick={() => update(() => model.scan())} disabled={running}>Complete one scan</button><button className="btn small ghost" onClick={() => setRunning(r => !r)} aria-pressed={running}>{running ? 'Pause scans' : 'Run scans'}</button></div><div className="lesson-settings"><div><span className="lesson-hint">Stop instruction (try the wrong one)</span><Seg label="Stop instruction" value={model.stopInstruction} options={['XIC', 'XIO']} onChange={v => update(() => { model.stopInstruction = v })} /></div><div><span className="lesson-hint">Holding branch</span><Seg label="Holding source" value={model.holdSource} options={['Feedback', 'Command']} onChange={v => update(() => { model.holdSource = v })} /></div></div></div>
    <div className="stats"><Stat k="Output command" n={model.command ? 'ON' : 'OFF'} /><Stat k="Contactor feedback" n={model.feedback ? 'ON' : 'OFF'} tone={model.command !== model.feedback ? 'bad' : 'ok'} s={model.command !== model.feedback ? 'command / feedback mismatch' : 'agrees with command'} /><Stat k="Physical motor" n={model.feedback ? 'RUNNING' : 'STOPPED'} /></div>
    <Suspense fallback={<div className="skeleton">Loading motor…</div>}><MachineScene kind="motor" active={model.feedback} /></Suspense>
    <div className="callout">Start → complete a scan → release Start → scan again. Feedback holds the rung. Now jam the contactor: an output command can remain true while the equipment never starts. Compare the two holding sources. This ordinary control model does not implement an emergency-stop safety circuit.</div>
  </>
}
