export const PROBES = ['Field switch', 'Input terminal', 'Input channel', 'Program tag', 'Output command', 'Load supply'] as const
export type Probe = typeof PROBES[number]
export const DIAGNOSES = ['Open input wire', 'Wrong input address', 'Inverted logic test', 'Missing load supply'] as const
export interface FaultCase { title: string; symptom: string; answer: typeof DIAGNOSES[number]; evidence: Record<Probe, string>; required: Probe[]; explanation: string }
export const FAULT_CASES: FaultCase[] = [
  { title: 'The switch closes. The lamp stays off.', symptom: 'The controller is in RUN. Closing the field switch should turn on the lamp, but it does not.', answer: 'Open input wire', evidence: { 'Field switch': 'The NO switch is physically closed; its supply side is at 24 V.', 'Input terminal': '0 V measured at the input terminal relative to common.', 'Input channel': 'Channel I0 indicator OFF. Live channel bit = 0.', 'Program tag': 'LampRequest is mapped to I0. LampRequest = 0.', 'Output command': 'XIC LampRequest is false. LampCommand = 0.', 'Load supply': '24 V load supply is available. Lamp circuit is intact.' }, required: ['Field switch', 'Input terminal'], explanation: 'The switch has closed and its supply is present, but no voltage reaches the terminal. Within this one-fault exercise, the input wire is open. The channel and program correctly report the missing signal.' },
  { title: 'The input LED is on. The program disagrees.', symptom: 'The switch is closed and the input module’s I0 indicator is on. The lamp is still off.', answer: 'Wrong input address', evidence: { 'Field switch': 'The NO switch is closed with 24 V at its outgoing terminal.', 'Input terminal': '24 V is present at input I0.', 'Input channel': 'I0 indicator ON. Live I0 bit = 1. Unused I1 = 0.', 'Program tag': 'LampRequest is mapped to I1, not the wired channel I0. LampRequest = 0.', 'Output command': 'XIC LampRequest is false. LampCommand = 0.', 'Load supply': '24 V load supply is available. Lamp circuit is intact.' }, required: ['Input channel', 'Program tag'], explanation: 'The physical channel is true, but the program reads a different address. Correct the mapping. Replacing the sensor would not fix this mismatch.' },
  { title: 'The lamp responds backwards.', symptom: 'Closing the switch turns the lamp off; opening it turns the lamp on. The intended behavior is the opposite.', answer: 'Inverted logic test', evidence: { 'Field switch': 'The NO switch is closed. Its outgoing terminal is at 24 V.', 'Input terminal': '24 V present. Opening the switch changes this to 0 V.', 'Input channel': 'I0 = 1 with the switch closed, 0 with it open.', 'Program tag': 'LampRequest correctly maps to I0 and follows it.', 'Output command': 'Program uses XIO LampRequest. With LampRequest = 1, the rung is false and LampCommand = 0.', 'Load supply': 'Load power and lamp are healthy. The lamp lights when the switch is open.' }, required: ['Program tag', 'Output command'], explanation: 'The tag follows the input correctly. XIO passes when the bit is zero, so this program inverts the intended response. For this stated requirement, use a test for a true bit.' },
  { title: 'The output is on. The lamp is dark.', symptom: 'The input and program look correct, and the output module indicator is on. The field lamp remains off.', answer: 'Missing load supply', evidence: { 'Field switch': 'The field switch is closed and its input supply is healthy.', 'Input terminal': '24 V at input I0.', 'Input channel': 'I0 indicator ON. Live channel bit = 1.', 'Program tag': 'LampRequest correctly maps to I0; its value is 1.', 'Output command': 'XIC is true. LampCommand = 1 and the output channel indicator is ON.', 'Load supply': 'The output’s separate load supply measures 0 V. Virtual continuity checks show the lamp and load wiring are intact.' }, required: ['Output command', 'Load supply'], explanation: 'An output indicator reports command/channel status, not proof that power reaches the load. Here the separate load supply is missing, while the lamp and wiring are intact.' },
]
export function assessFault(c: FaultCase, probes: Probe[], answer: string) {
  if (!c.required.every(p => probes.includes(p))) return { correct: false, message: 'Gather evidence on both sides of the suspected boundary before concluding. The diagnosis needs a supporting pair of observations.' }
  if (answer !== c.answer) return { correct: false, message: 'That cause does not fit the collected evidence. Compare the field condition, input channel, program tag, command and load supply.' }
  return { correct: true, message: c.explanation }
}
